/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.g2sky.pgd.intf.thrift.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CmdType implements org.apache.thrift.TEnum {
  APPCMDREQ(1),
  APPCMDRSP(2),
  COMMCMDREQ(3),
  COMMCMDRSP(4);

  private final int value;

  private CmdType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CmdType findByValue(int value) { 
    switch (value) {
      case 1:
        return APPCMDREQ;
      case 2:
        return APPCMDRSP;
      case 3:
        return COMMCMDREQ;
      case 4:
        return COMMCMDRSP;
      default:
        return null;
    }
  }
}
