/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.g2sky.pgd.intf.thrift.common;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DeviceInfo implements org.apache.thrift.TBase<DeviceInfo, DeviceInfo._Fields>, java.io.Serializable, Cloneable, Comparable<DeviceInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DeviceInfo");

  private static final org.apache.thrift.protocol.TField IMSI_FIELD_DESC = new org.apache.thrift.protocol.TField("imsi", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ISENCRYPTED_FIELD_DESC = new org.apache.thrift.protocol.TField("isencrypted", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField ENCRYPTION_FACTOR_FIELD_DESC = new org.apache.thrift.protocol.TField("encryptionFactor", org.apache.thrift.protocol.TType.BYTE, (short)3);
  private static final org.apache.thrift.protocol.TField IP_FIELD_DESC = new org.apache.thrift.protocol.TField("ip", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DeviceInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DeviceInfoTupleSchemeFactory());
  }

  public String imsi; // required
  public boolean isencrypted; // required
  public byte encryptionFactor; // required
  public String ip; // required
  public int port; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IMSI((short)1, "imsi"),
    ISENCRYPTED((short)2, "isencrypted"),
    ENCRYPTION_FACTOR((short)3, "encryptionFactor"),
    IP((short)4, "ip"),
    PORT((short)5, "port");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IMSI
          return IMSI;
        case 2: // ISENCRYPTED
          return ISENCRYPTED;
        case 3: // ENCRYPTION_FACTOR
          return ENCRYPTION_FACTOR;
        case 4: // IP
          return IP;
        case 5: // PORT
          return PORT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ISENCRYPTED_ISSET_ID = 0;
  private static final int __ENCRYPTIONFACTOR_ISSET_ID = 1;
  private static final int __PORT_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IMSI, new org.apache.thrift.meta_data.FieldMetaData("imsi", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ISENCRYPTED, new org.apache.thrift.meta_data.FieldMetaData("isencrypted", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ENCRYPTION_FACTOR, new org.apache.thrift.meta_data.FieldMetaData("encryptionFactor", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.IP, new org.apache.thrift.meta_data.FieldMetaData("ip", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DeviceInfo.class, metaDataMap);
  }

  public DeviceInfo() {
  }

  public DeviceInfo(
    String imsi,
    boolean isencrypted,
    byte encryptionFactor,
    String ip,
    int port)
  {
    this();
    this.imsi = imsi;
    this.isencrypted = isencrypted;
    setIsencryptedIsSet(true);
    this.encryptionFactor = encryptionFactor;
    setEncryptionFactorIsSet(true);
    this.ip = ip;
    this.port = port;
    setPortIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DeviceInfo(DeviceInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetImsi()) {
      this.imsi = other.imsi;
    }
    this.isencrypted = other.isencrypted;
    this.encryptionFactor = other.encryptionFactor;
    if (other.isSetIp()) {
      this.ip = other.ip;
    }
    this.port = other.port;
  }

  public DeviceInfo deepCopy() {
    return new DeviceInfo(this);
  }

  @Override
  public void clear() {
    this.imsi = null;
    setIsencryptedIsSet(false);
    this.isencrypted = false;
    setEncryptionFactorIsSet(false);
    this.encryptionFactor = 0;
    this.ip = null;
    setPortIsSet(false);
    this.port = 0;
  }

  public String getImsi() {
    return this.imsi;
  }

  public DeviceInfo setImsi(String imsi) {
    this.imsi = imsi;
    return this;
  }

  public void unsetImsi() {
    this.imsi = null;
  }

  /** Returns true if field imsi is set (has been assigned a value) and false otherwise */
  public boolean isSetImsi() {
    return this.imsi != null;
  }

  public void setImsiIsSet(boolean value) {
    if (!value) {
      this.imsi = null;
    }
  }

  public boolean isIsencrypted() {
    return this.isencrypted;
  }

  public DeviceInfo setIsencrypted(boolean isencrypted) {
    this.isencrypted = isencrypted;
    setIsencryptedIsSet(true);
    return this;
  }

  public void unsetIsencrypted() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISENCRYPTED_ISSET_ID);
  }

  /** Returns true if field isencrypted is set (has been assigned a value) and false otherwise */
  public boolean isSetIsencrypted() {
    return EncodingUtils.testBit(__isset_bitfield, __ISENCRYPTED_ISSET_ID);
  }

  public void setIsencryptedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISENCRYPTED_ISSET_ID, value);
  }

  public byte getEncryptionFactor() {
    return this.encryptionFactor;
  }

  public DeviceInfo setEncryptionFactor(byte encryptionFactor) {
    this.encryptionFactor = encryptionFactor;
    setEncryptionFactorIsSet(true);
    return this;
  }

  public void unsetEncryptionFactor() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ENCRYPTIONFACTOR_ISSET_ID);
  }

  /** Returns true if field encryptionFactor is set (has been assigned a value) and false otherwise */
  public boolean isSetEncryptionFactor() {
    return EncodingUtils.testBit(__isset_bitfield, __ENCRYPTIONFACTOR_ISSET_ID);
  }

  public void setEncryptionFactorIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ENCRYPTIONFACTOR_ISSET_ID, value);
  }

  public String getIp() {
    return this.ip;
  }

  public DeviceInfo setIp(String ip) {
    this.ip = ip;
    return this;
  }

  public void unsetIp() {
    this.ip = null;
  }

  /** Returns true if field ip is set (has been assigned a value) and false otherwise */
  public boolean isSetIp() {
    return this.ip != null;
  }

  public void setIpIsSet(boolean value) {
    if (!value) {
      this.ip = null;
    }
  }

  public int getPort() {
    return this.port;
  }

  public DeviceInfo setPort(int port) {
    this.port = port;
    setPortIsSet(true);
    return this;
  }

  public void unsetPort() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return EncodingUtils.testBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  public void setPortIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PORT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IMSI:
      if (value == null) {
        unsetImsi();
      } else {
        setImsi((String)value);
      }
      break;

    case ISENCRYPTED:
      if (value == null) {
        unsetIsencrypted();
      } else {
        setIsencrypted((Boolean)value);
      }
      break;

    case ENCRYPTION_FACTOR:
      if (value == null) {
        unsetEncryptionFactor();
      } else {
        setEncryptionFactor((Byte)value);
      }
      break;

    case IP:
      if (value == null) {
        unsetIp();
      } else {
        setIp((String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IMSI:
      return getImsi();

    case ISENCRYPTED:
      return Boolean.valueOf(isIsencrypted());

    case ENCRYPTION_FACTOR:
      return Byte.valueOf(getEncryptionFactor());

    case IP:
      return getIp();

    case PORT:
      return Integer.valueOf(getPort());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IMSI:
      return isSetImsi();
    case ISENCRYPTED:
      return isSetIsencrypted();
    case ENCRYPTION_FACTOR:
      return isSetEncryptionFactor();
    case IP:
      return isSetIp();
    case PORT:
      return isSetPort();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DeviceInfo)
      return this.equals((DeviceInfo)that);
    return false;
  }

  public boolean equals(DeviceInfo that) {
    if (that == null)
      return false;

    boolean this_present_imsi = true && this.isSetImsi();
    boolean that_present_imsi = true && that.isSetImsi();
    if (this_present_imsi || that_present_imsi) {
      if (!(this_present_imsi && that_present_imsi))
        return false;
      if (!this.imsi.equals(that.imsi))
        return false;
    }

    boolean this_present_isencrypted = true;
    boolean that_present_isencrypted = true;
    if (this_present_isencrypted || that_present_isencrypted) {
      if (!(this_present_isencrypted && that_present_isencrypted))
        return false;
      if (this.isencrypted != that.isencrypted)
        return false;
    }

    boolean this_present_encryptionFactor = true;
    boolean that_present_encryptionFactor = true;
    if (this_present_encryptionFactor || that_present_encryptionFactor) {
      if (!(this_present_encryptionFactor && that_present_encryptionFactor))
        return false;
      if (this.encryptionFactor != that.encryptionFactor)
        return false;
    }

    boolean this_present_ip = true && this.isSetIp();
    boolean that_present_ip = true && that.isSetIp();
    if (this_present_ip || that_present_ip) {
      if (!(this_present_ip && that_present_ip))
        return false;
      if (!this.ip.equals(that.ip))
        return false;
    }

    boolean this_present_port = true;
    boolean that_present_port = true;
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (this.port != that.port)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(DeviceInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetImsi()).compareTo(other.isSetImsi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImsi()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imsi, other.imsi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsencrypted()).compareTo(other.isSetIsencrypted());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsencrypted()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isencrypted, other.isencrypted);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEncryptionFactor()).compareTo(other.isSetEncryptionFactor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEncryptionFactor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.encryptionFactor, other.encryptionFactor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIp()).compareTo(other.isSetIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ip, other.ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPort()).compareTo(other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DeviceInfo(");
    boolean first = true;

    sb.append("imsi:");
    if (this.imsi == null) {
      sb.append("null");
    } else {
      sb.append(this.imsi);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isencrypted:");
    sb.append(this.isencrypted);
    first = false;
    if (!first) sb.append(", ");
    sb.append("encryptionFactor:");
    sb.append(this.encryptionFactor);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ip:");
    if (this.ip == null) {
      sb.append("null");
    } else {
      sb.append(this.ip);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("port:");
    sb.append(this.port);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DeviceInfoStandardSchemeFactory implements SchemeFactory {
    public DeviceInfoStandardScheme getScheme() {
      return new DeviceInfoStandardScheme();
    }
  }

  private static class DeviceInfoStandardScheme extends StandardScheme<DeviceInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DeviceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IMSI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imsi = iprot.readString();
              struct.setImsiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ISENCRYPTED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isencrypted = iprot.readBool();
              struct.setIsencryptedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ENCRYPTION_FACTOR
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.encryptionFactor = iprot.readByte();
              struct.setEncryptionFactorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ip = iprot.readString();
              struct.setIpIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.port = iprot.readI32();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DeviceInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.imsi != null) {
        oprot.writeFieldBegin(IMSI_FIELD_DESC);
        oprot.writeString(struct.imsi);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ISENCRYPTED_FIELD_DESC);
      oprot.writeBool(struct.isencrypted);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ENCRYPTION_FACTOR_FIELD_DESC);
      oprot.writeByte(struct.encryptionFactor);
      oprot.writeFieldEnd();
      if (struct.ip != null) {
        oprot.writeFieldBegin(IP_FIELD_DESC);
        oprot.writeString(struct.ip);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PORT_FIELD_DESC);
      oprot.writeI32(struct.port);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DeviceInfoTupleSchemeFactory implements SchemeFactory {
    public DeviceInfoTupleScheme getScheme() {
      return new DeviceInfoTupleScheme();
    }
  }

  private static class DeviceInfoTupleScheme extends TupleScheme<DeviceInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DeviceInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetImsi()) {
        optionals.set(0);
      }
      if (struct.isSetIsencrypted()) {
        optionals.set(1);
      }
      if (struct.isSetEncryptionFactor()) {
        optionals.set(2);
      }
      if (struct.isSetIp()) {
        optionals.set(3);
      }
      if (struct.isSetPort()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetImsi()) {
        oprot.writeString(struct.imsi);
      }
      if (struct.isSetIsencrypted()) {
        oprot.writeBool(struct.isencrypted);
      }
      if (struct.isSetEncryptionFactor()) {
        oprot.writeByte(struct.encryptionFactor);
      }
      if (struct.isSetIp()) {
        oprot.writeString(struct.ip);
      }
      if (struct.isSetPort()) {
        oprot.writeI32(struct.port);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DeviceInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.imsi = iprot.readString();
        struct.setImsiIsSet(true);
      }
      if (incoming.get(1)) {
        struct.isencrypted = iprot.readBool();
        struct.setIsencryptedIsSet(true);
      }
      if (incoming.get(2)) {
        struct.encryptionFactor = iprot.readByte();
        struct.setEncryptionFactorIsSet(true);
      }
      if (incoming.get(3)) {
        struct.ip = iprot.readString();
        struct.setIpIsSet(true);
      }
      if (incoming.get(4)) {
        struct.port = iprot.readI32();
        struct.setPortIsSet(true);
      }
    }
  }

}

