/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.g2sky.pgd.intf.thrift.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MsgType implements org.apache.thrift.TEnum {
  LOGIN(1),
  COMMAND(2);

  private final int value;

  private MsgType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MsgType findByValue(int value) { 
    switch (value) {
      case 1:
        return LOGIN;
      case 2:
        return COMMAND;
      default:
        return null;
    }
  }
}
